CREATE TABLE "SYSTEM"."CUSTOMER_REVIEWS_FOOD" (
    "C_ID" VARCHAR2(10),
    "FOOD_ID" VARCHAR2(50),
    "C_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    "V_REPLY" VARCHAR2(4000),
    "V_REPLY_DATE" TIMESTAMP (6),
    "FOOD_REVIEW" VARCHAR2(4000),
    "FOOD_RATING" NUMBER(1, 0) DEFAULT 0,
    PRIMARY KEY ("FOOD_ID", "C_ID") USING INDEX ENABLE,
    FOREIGN KEY ("C_ID") REFERENCES "SYSTEM"."CUSTOMERS" ("C_ID") ON DELETE CASCADE ENABLE,
    FOREIGN KEY ("FOOD_ID") REFERENCES "SYSTEM"."FOOD" ("FOOD_ID") ON DELETE CASCADE ENABLE
);