CREATE TABLE "SYSTEM"."CUSTOMER_REVIEWS" (
    "CUSTOMER_ID" NUMBER,
    "NAME" VARCHAR2(100),
    "REVIEW_MESSAGE" VARCHAR2(1000),
    "RATING" NUMBER(1, 0),
    PRIMARY KEY ("CUSTOMER_ID") USING INDEX ENABLE
);