CREATE OR REPLACE FUNCTION GET_RECENT_VENDORS_COUNT RETURN NUMBER IS
    TOTAL_VENDORS NUMBER;
BEGIN
    SELECT
        COUNT(V_ID) INTO TOTAL_VENDORS
    FROM
        VENDORS
    WHERE
        (SYSDATE - JOIN_DATE) <= INTERVAL '1' DAY;
    RETURN TOTAL_VENDORS;
END;
/