CREATE OR REPLACE FUNCTION GET_RECENT_CUSTOMERS_COUNT RETURN NUMBER IS
    TOTAL_CUSTOMERS NUMBER;
BEGIN
    SELECT
        COUNT(C_ID) INTO TOTAL_CUSTOMERS
    FROM
        CUSTOMERS
    WHERE
        (SYSDATE - JOIN_DATE) <= INTERVAL '1' DAY;
    RETURN TOTAL_CUSTOMERS;
END;
/