CREATE OR REPLACE TYPE SHOP_INFO_TYPE AS
    OBJECT (
        STALL_NAME VARCHAR2(100),
        V_FIRST_NAME VARCHAR2(50),
        V_LAST_NAME VARCHAR2(50),
        AREA VARCHAR2(200),
        CITY VARCHAR2(50),
        DISTRICT VARCHAR2(50),
        STALL_TITLE VARCHAR2(1000),
        STALL_PIC VARCHAR2(255),
        LOCATION_URL VARCHAR2(255),
        STATUS VARCHAR2(10), -- Removed DEFAULT 'open'
        SHOP_DESCRIPTION VARCHAR2(4000)
    );
    CREATE OR REPLACE TYPE PHONE_NUMBER_TYPE AS OBJECT (
        PHONE_NUMBER VARCHAR2(20)
    );
    CREATE OR REPLACE TYPE PHONE_NUMBER_LIST_TYPE AS TABLE OF PHONE_NUMBER_TYPE;
    CREATE OR REPLACE TYPE SHOP_INFO_TYPE AS OBJECT (
        STALL_NAME VARCHAR2(100),
        V_FIRST_NAME VARCHAR2(50),
        V_LAST_NAME VARCHAR2(50),
        AREA VARCHAR2(200),
        CITY VARCHAR2(50),
        DISTRICT VARCHAR2(50),
        STALL_TITLE VARCHAR2(1000),
        STALL_PIC VARCHAR2(255),
        LOCATION_URL VARCHAR2(255),
        STATUS VARCHAR2(10),
        SHOP_DESCRIPTION VARCHAR2(4000),
        PHONE_NUMBERS PHONE_NUMBER_LIST_TYPE
    );