CREATE TABLE "SYSTEM"."UPLOADED_VIDEOS" (
    "VIDEO_ID" VARCHAR2(100),
    "C_ID" VARCHAR2(100) NOT NULL ENABLE,
    "VIDEO_TITLE" VARCHAR2(255) NOT NULL ENABLE,
    "VIDEO_DESCRIPTION" VARCHAR2(1000),
    "TAGS" VARCHAR2(500),
    "VIDEO_LINKS" VARCHAR2(1000),
    "IMAGE_LINKS" VARCHAR2(255),
    "UPLOAD_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    PRIMARY KEY ("VIDEO_ID") USING INDEX ENABLE
);