CREATE OR REPLACE VIEW VENDOR_FOOD_DETAILS_VIEW AS
SELECT 
    V.V_ID,
    V.DISPLAY_NAME AS VENDOR_NAME,
    F.FOOD_ID,
    F.FOOD_NAME,
    F.PRICE,
    F.RATING,
    F.AVAILABILITY
FROM 
    VENDOR_SELLS_FOOD VSF
JOIN 
    VENDORS V ON VSF.V_ID = V.V_ID
JOIN 
    FOOD F ON VSF.FOOD_ID = F.FOOD_ID;



    CREATE OR REPLACE VIEW VENDOR_PROMOTIONS_VIEW AS
SELECT 
    UPV.V_ID,
    V.DISPLAY_NAME AS VENDOR_NAME,
    UPV.VIDEO_ID
FROM 
    USER_PROMOTES_VENDOR UPV
JOIN 
    VENDORS V ON UPV.V_ID = V.V_ID;





    CREATE OR REPLACE VIEW CUSTOMER_FOOD_REVIEWS_VIEW AS
SELECT 
    C.C_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    F.FOOD_NAME,
    R.FOOD_REVIEW,
    R.FOOD_RATING,
    R.C_DATE
FROM 
    CUSTOMER_REVIEWS_FOOD R
JOIN 
    CUSTOMERS C ON R.C_ID = C.C_ID
JOIN 
    FOOD F ON R.FOOD_ID = F.FOOD_ID;



    CREATE OR REPLACE VIEW VENDOR_CUSTOMER_REVIEWS_VIEW AS
SELECT 
    CRV.C_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    CRV.V_ID,
    V.DISPLAY_NAME AS VENDOR_NAME,
    CRV.REVIEW_MESSAGE,
    CRV.RATING,
    CRV.C_DATE,
    CRV.REPLY,
    CRV.V_REPLY_DATE
FROM 
    CUSTOMERREVIEWSVENDOR CRV
JOIN 
    CUSTOMERS C ON CRV.C_ID = C.C_ID
JOIN 
    VENDORS V ON CRV.V_ID = V.V_ID;